# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_page2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog, QMainWindow
from PyQt5.QtCore import pyqtSignal,Qt,QPoint
import icons
import sys
# from Custom_title_bar import *    # no need as we have written the code directly here in this file 

class Page2_ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#header_1{\n"
"background-color: #e5f1f8;\n"
"border-bottom:1px solid #d0d0d0;\n"
"}\n"
"#header_2{\n"
"background-color: #e5f1f8;\n"
"border-bottom:1px solid #d0d0d0;\n"
"}\n"
"\n"
"#close_btn{\n"
"border:none;\n"
"\n"
"}\n"
"#minimize_btn{\n"
"border:none;\n"
"\n"
"}\n"
"#cancel_btn{\n"
"border:none;\n"
"background-color:#80bbdb;\n"
"border-radius:15px;\n"
"}\n"
"#cancel_btn:hover{\n"
"background-color:#2b87b6;\n"
"color:#e5f1f8;\n"
"}\n"
"#next_btn{\n"
"border:none;\n"
"background-color:#80bbdb;\n"
"border-radius:15px;\n"
"}\n"
"#next_btn:hover{\n"
"background-color:#2b87b6;\n"
"color:#e5f1f8;\n"
"}\n"
"\n"
"/*Body */\n"
"\n"
"#body{\n"
"background-color:#e5f1f8;\n"
"}\n"
"\n"
"#select_files{\n"
"background-color:#24536a;\n"
"color:#e5f1f8;\n"
"border-radius:20px;\n"
"}\n"
"#select_files:hover{\n"
"background-color:#80bbdb;\n"
"color:#080e12;\n"
"}\n"
"#select_folders{\n"
"background-color:#24536a;\n"
"color:#e5f1f8;\n"
"border-radius:20px;\n"
"}\n"
"#select_folders:hover{\n"
"background-color:#80bbdb;\n"
"color:#080e12;\n"
"}\n"
"#ignore_files{\n"
"background-color:#24536a;\n"
"color:#e5f1f8;\n"
"border-radius:20px;\n"
"}\n"
"#ignore_files:hover{\n"
"background-color:#80bbdb;\n"
"color:#080e12;\n"
"}\n"
"#ignore_folders{\n"
"background-color:#24536a;\n"
"color:#e5f1f8;\n"
"border-radius:20px;\n"
"}\n"
"#ignore_folders:hover{\n"
"background-color:#80bbdb;\n"
"color:#080e12;\n"
"}\n"
"\n"
"#display_selected_files_listWidget{\n"
"border:1px solid #d0d0d0;\n"
"background-color:#ADD8E6;\n"
"color:#080e12;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"#display_ignored_files_listwidget{\n"
"border:1px solid #d0d0d0;\n"
"background-color:#ADD8E6;\n"
"color:#080e12;\n"
"border-radius:10px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_1 = QtWidgets.QFrame(self.centralwidget)
        self.header_1.setMinimumSize(QtCore.QSize(0, 52))
        self.header_1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.header_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_1.setObjectName("header_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.header_1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.header_1)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.minimize_btn = QtWidgets.QPushButton(self.frame_8)
        self.minimize_btn.setMinimumSize(QtCore.QSize(45, 45))
        self.minimize_btn.setMaximumSize(QtCore.QSize(45, 45))
        self.minimize_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimize_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"icons\minimize_btn2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_btn.setIcon(icon)
        self.minimize_btn.setIconSize(QtCore.QSize(30, 30))
        self.minimize_btn.setObjectName("minimize_btn")
        self.verticalLayout_5.addWidget(self.minimize_btn)
        self.horizontalLayout.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.close_btn = QtWidgets.QPushButton(self.frame_9)
        self.close_btn.setMinimumSize(QtCore.QSize(45, 45))
        self.close_btn.setMaximumSize(QtCore.QSize(45, 45))
        self.close_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(r"icons\bluest-close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon1)
        self.close_btn.setIconSize(QtCore.QSize(30, 30))
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_3.addWidget(self.close_btn)
        self.horizontalLayout.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_4, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.header_1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.header_2 = QtWidgets.QFrame(self.frame_2)
        self.header_2.setMinimumSize(QtCore.QSize(900, 59))
        self.header_2.setMaximumSize(QtCore.QSize(700, 16777215))
        self.header_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_2.setObjectName("header_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_2)
        self.horizontalLayout_2.setContentsMargins(9, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancel_btn = QtWidgets.QPushButton(self.header_2)
        self.cancel_btn.setMinimumSize(QtCore.QSize(0, 45))
        self.cancel_btn.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(15)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.backup_label = QtWidgets.QLabel(self.header_2)
        self.backup_label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.backup_label.setFont(font)
        self.backup_label.setAlignment(QtCore.Qt.AlignCenter)
        self.backup_label.setObjectName("backup_label")
        self.horizontalLayout_2.addWidget(self.backup_label)
        self.next_btn = QtWidgets.QPushButton(self.header_2)
        self.next_btn.setMinimumSize(QtCore.QSize(0, 45))
        self.next_btn.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(15)
        self.next_btn.setFont(font)
        self.next_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout_2.addWidget(self.next_btn)
        self.verticalLayout_3.addWidget(self.header_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.body = QtWidgets.QFrame(self.centralwidget)
        self.body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName("body")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.body)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.body)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_11 = QtWidgets.QFrame(self.frame_7)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.select_files_label = QtWidgets.QLabel(self.frame_11)
        self.select_files_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.select_files_label.setFont(font)
        self.select_files_label.setAlignment(QtCore.Qt.AlignCenter)
        self.select_files_label.setObjectName("select_files_label")
        self.verticalLayout_7.addWidget(self.select_files_label)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.select_files = QtWidgets.QPushButton(self.frame_13)
        self.select_files.setMinimumSize(QtCore.QSize(200, 170))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(15)
        self.select_files.setFont(font)
        self.select_files.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/files.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.select_files.setIcon(icon2)
        self.select_files.setIconSize(QtCore.QSize(25, 25))
        self.select_files.setObjectName("select_files")
        self.horizontalLayout_6.addWidget(self.select_files)
        self.select_folders = QtWidgets.QPushButton(self.frame_13)
        self.select_folders.setMinimumSize(QtCore.QSize(200, 170))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(15)
        self.select_folders.setFont(font)
        self.select_folders.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.select_folders.setObjectName("select_folders")
        self.horizontalLayout_6.addWidget(self.select_folders)
        self.verticalLayout_7.addWidget(self.frame_13)
        self.horizontalLayout_4.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_7)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.display_selected_files_listWidget = QtWidgets.QListWidget(self.frame_12)
        self.display_selected_files_listWidget.setGeometry(QtCore.QRect(12, 5, 430, 230))
        self.display_selected_files_listWidget.setObjectName("display_selected_files_listWidget")
        self.horizontalLayout_4.addWidget(self.frame_12)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_14 = QtWidgets.QFrame(self.frame_10)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ignore_files_label = QtWidgets.QLabel(self.frame_14)
        self.ignore_files_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.ignore_files_label.setFont(font)
        self.ignore_files_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ignore_files_label.setObjectName("ignore_files_label")
        self.verticalLayout_8.addWidget(self.ignore_files_label)
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ignore_files = QtWidgets.QPushButton(self.frame_16)
        self.ignore_files.setMinimumSize(QtCore.QSize(200, 170))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(15)
        self.ignore_files.setFont(font)
        self.ignore_files.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ignore_files.setObjectName("ignore_files")
        self.horizontalLayout_7.addWidget(self.ignore_files)
        self.ignore_folders = QtWidgets.QPushButton(self.frame_16)
        self.ignore_folders.setMinimumSize(QtCore.QSize(200, 170))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(15)
        self.ignore_folders.setFont(font)
        self.ignore_folders.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ignore_folders.setObjectName("ignore_folders")
        self.horizontalLayout_7.addWidget(self.ignore_folders)
        self.verticalLayout_8.addWidget(self.frame_16)
        self.horizontalLayout_5.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_10)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.display_ignored_files_listwidget = QtWidgets.QListWidget(self.frame_15)
        self.display_ignored_files_listwidget.setGeometry(QtCore.QRect(12, 5, 430, 230))
        self.display_ignored_files_listwidget.setObjectName("display_ignored_files_listwidget")
        self.horizontalLayout_5.addWidget(self.frame_15)
        self.verticalLayout_6.addWidget(self.frame_10)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.body)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.selectedFiles = []
        self.selectedFolders = []
        self.ignorePaths = []


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cancel_btn.setText(_translate("MainWindow", "Cancel"))
        self.backup_label.setText(_translate("MainWindow", "Back Up"))
        self.next_btn.setText(_translate("MainWindow", "Next"))
        self.select_files_label.setText(_translate("MainWindow", "Select Files / Folders "))
        self.select_files.setText(_translate("MainWindow", "Select Files"))
        self.select_folders.setText(_translate("MainWindow", "Select Folders "))
        self.ignore_files_label.setText(_translate("MainWindow", "Ignore files / folders "))
        self.ignore_files.setText(_translate("MainWindow", "Ignore Files"))
        self.ignore_folders.setText(_translate("MainWindow", "Ignore Folders "))

class MainWindow(QMainWindow, Page2_ui_MainWindow):

    # Define a custom   signal 
    goBackSignal = pyqtSignal()
    goToNextPageSignal = pyqtSignal()

    def __init__(self):
        super().__init__()

        # this code custamizes the window title 
        # self.setWindowTitle("Custom Title Bar")  # Set window title
        # self.resize(400, 200)  # Set initial size
        # self.setWindowFlags(Qt.FramelessWindowHint)  # Make window frameless
        # windo title customization ends here 

        self.setupUi(self)

        # Connect signals to slots
        self.select_files.clicked.connect(self.selectFiles)
        self.select_folders.clicked.connect(self.selectFolders)

        self.display_selected_files_listWidget.itemClicked.connect(self.confirmRemoveSelectedItem)


        # self.ignore_files.clicked.connect(self.selectIgnoreFiles)
        # self.ignore_folders.clicked.connect(self.selectIgnoreFolders)

        # self.display_ignored_files_listwidget.itemClicked.connect(self.confirmRemoveSelectedItem)


        # Connect the cancel button to a new method that emits the signal
        # i.e when clicked this button it calls a function emiGoBackSignal ..which emits the custom signal 
        self.cancel_btn.clicked.connect(self.emitGoBackSignal)
        # end of connecting the custom signal 
        # i.e. when clicked it emmits a a goBAckSignal ..this signal is emitied by the MainWindow Class 
        # program is written in the Main Application file to listen to this signal ...when receved this signal it will call a function to hide the current window and show the prev window 


        # calling the emitGoToNextPageSignal function when clicked next_btn ...which inturn emits teh the custom goToNextPageSignal
        self.next_btn.clicked.connect(self.emitGoToNextPageSignal)


        # conneecting the close_btn ans minimize_btn so that the custome title bar works 
    #     self.close_btn.clicked.connect(self.close)

    #     self.minimize_btn.clicked.connect(self.showMinimized)
    #    # the customization end here 
        

    #     # codes for dragable window .....connections 
    #     # Initialize the old position
    #     self._old_pos = None


    #      # Connect mouse events to the title bar or another element meant to be draggable
    #     self.header_1.mousePressEvent = self.mousePressEvent
    #     self.header_1.mouseMoveEvent = self.mouseMoveEvent
    #     self.header_1.mouseReleaseEvent = self.mouseReleaseEvent

        # end of dragable window ..connections 



        # Add any other connections you need

    # # dragable window functions 
    # def mousePressEvent(self, event):
    #     if event.button() == Qt.LeftButton:
    #         self._old_pos = event.globalPos()

    # def mouseMoveEvent(self, event):
    #     if not self._old_pos:
    #         return
    #     delta = event.globalPos() - self._old_pos
    #     self.move(self.x() + delta.x(), self.y() + delta.y())
    #     self._old_pos = event.globalPos()

    # def mouseReleaseEvent(self, event):
    #     self._old_pos = None

    # # dragable window functions end here 
        
    # # custom signal functions 

    def emitGoToNextPageSignal(self):
        self.goToNextPageSignal.emit()

    def emitGoBackSignal(self):
        # Emit the custom signal
        self.goBackSignal.emit()

    # End of custom signal functions 

    
    def selectFiles(self):
        files, _ = QFileDialog.getOpenFileNames(self, "Select Files")
        self.selectedFiles.extend(files)
        self.updateSelectedPathsList()

    def selectFolders(self):
        folder = QFileDialog.getExistingDirectory(self, "Select Folder")
        if folder:
            self.selectedFolders.append(folder)
            self.updateSelectedPathsList()

    def updateSelectedPathsList(self):
        self.display_selected_files_listWidget.clear()
        for file in self.selectedFiles:
            self.display_selected_files_listWidget.addItem(file)
        for folder in self.selectedFolders:
            self.display_selected_files_listWidget.addItem(folder)

    # def selectIgnoreFiles(self):
    #     files, _ = QFileDialog.getOpenFileNames(self, "Select Files to Ignore")
    #     self.ignorePaths.extend(files)
    #     self.updateIgnoreList()

    # def selectIgnoreFolders(self):
    #     folder = QFileDialog.getExistingDirectory(self, "Select Folder to Ignore")
    #     if folder:
    #         self.ignorePaths.append(folder)
    #         self.updateIgnoreList()

    # def updateIgnoreList(self):
    #     self.display_ignored_files_listwidget.clear()
    #     for path in self.ignorePaths:
    #         self.display_ignored_files_listwidget.addItem(path)


    def confirmRemoveSelectedItem(self, item):
        response = QMessageBox.question(self, "Remove Item", "Are you sure you want to remove this item?")
        if response == QMessageBox.Yes:
            self.removeSelectedItem(item.text())

    # def confirmRemoveIgnoredItem(self, item):
    #     response = QMessageBox.question(self, "Remove Ignored Item", "Are you sure you want to remove this item from the ignore list?")
    #     if response == QMessageBox.Yes:
    #         self.removeIgnoredItem(item.text())


    def removeSelectedItem(self, text):
        if text in self.selectedFiles:
            self.selectedFiles.remove(text)
        elif text in self.selectedFolders:
            self.selectedFolders.remove(text)
        self.updateSelectedPathsList()

    # def removeIgnoredItem(self, text):
    #     if text in self.ignorePaths:
    #         self.ignorePaths.remove(text)
    #     self.updateIgnoreList()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Page2_ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
        
# if __name__ == "__main__":
#     import sys
#     app = QApplication(sys.argv)
#     window = CustomMainWindow(Ui_MainWindow)
#     window.show()
#     sys.exit(app.exec())
