# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Page3-5_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Page3_5_ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("/* Header 1 */\n"
"\n"
"\n"
"#header{\n"
"background-color:#105857;\n"
"}\n"
"\n"
"#cancel_btn{\n"
"color:white;\n"
"border:none;\n"
"background-color:#0c4140;\n"
"border-radius:10px;;\n"
"}\n"
"\n"
"#cancel_btn:hover{\n"
"background-color:#25827c;\n"
"}\n"
"\n"
"#backup_btn{\n"
"color:white;\n"
"border:none;\n"
"background-color:#0c4140;\n"
"border-radius:10px;;\n"
"}\n"
"\n"
"#backup_btn:hover{\n"
"background-color:#25827c;\n"
"}\n"
"\n"
"#back_btn{\n"
"border:none;\n"
"background-color:#9eb1b1;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"#back_btn:hover{\n"
"background-color:#d1d2d2;\n"
"}\n"
"\n"
"#schedule_label{\n"
"color:white;\n"
"padding-right:35px;\n"
"}\n"
"\n"
"/*body*/\n"
"#body{\n"
"background-color:#e0e2e3;\n"
"}\n"
"\n"
"#frame_5{\n"
"background-color: white;\n"
"border-top-left-radius:30px;\n"
"border-top-right-radius:30px;\n"
"border-top: 2px solid #BDC3CB;\n"
"border-right: 2px solid #BDC3CB;\n"
"border-left: 2px solid #BDC3CB;\n"
"}\n"
"\n"
"#frame_6{\n"
"background-color:white;\n"
"border-right: 2px solid #BDC3CB;\n"
"border-left: 2px solid #BDC3CB;\n"
"}\n"
"\n"
"#frame_7{\n"
"background-color: white;\n"
"border-bottom-left-radius:30px;\n"
"border-bottom-right-radius:30px;\n"
"border-bottom: 2px solid #BDC3CB;\n"
"border-right: 2px solid #BDC3CB;\n"
"border-left: 2px solid #BDC3CB;\n"
"}\n"
"\n"
"#When_select_btn,#keep_select_btn{\n"
"border:none;\n"
"background-color:#9eb1b1;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"#When_select_btn:hover,#keep_select_btn:hover{\n"
"background-color:#d1d2d2;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 60))
        self.header.setMaximumSize(QtCore.QSize(16777215, 60))
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.header)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.header)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_btn = QtWidgets.QPushButton(self.frame_3)
        self.cancel_btn.setMinimumSize(QtCore.QSize(200, 45))
        self.cancel_btn.setMaximumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(15)
        font.setBold(False)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.schedule_label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        self.schedule_label.setFont(font)
        self.schedule_label.setAlignment(QtCore.Qt.AlignCenter)
        self.schedule_label.setObjectName("schedule_label")
        self.horizontalLayout.addWidget(self.schedule_label)
        self.back_btn = QtWidgets.QPushButton(self.frame_3)
        self.back_btn.setMinimumSize(QtCore.QSize(100, 45))
        self.back_btn.setMaximumSize(QtCore.QSize(100, 45))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(15)
        self.back_btn.setFont(font)
        self.back_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout.addWidget(self.back_btn)
        self.backup_btn = QtWidgets.QPushButton(self.frame_3)
        self.backup_btn.setMinimumSize(QtCore.QSize(200, 45))
        self.backup_btn.setMaximumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(15)
        self.backup_btn.setFont(font)
        self.backup_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backup_btn.setObjectName("backup_btn")
        self.horizontalLayout.addWidget(self.backup_btn)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.header)
        self.body = QtWidgets.QFrame(self.centralwidget)
        self.body.setMinimumSize(QtCore.QSize(0, 540))
        self.body.setMaximumSize(QtCore.QSize(16777215, 540))
        self.body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName("body")
        self.frame_4 = QtWidgets.QFrame(self.body)
        self.frame_4.setGeometry(QtCore.QRect(110, 40, 700, 450))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.when_backup_label = QtWidgets.QLabel(self.frame_5)
        self.when_backup_label.setGeometry(QtCore.QRect(50, 50, 234, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.when_backup_label.setFont(font)
        self.when_backup_label.setObjectName("when_backup_label")
        self.whentobackup = QtWidgets.QDateTimeEdit(self.frame_5)
        self.whentobackup.setGeometry(QtCore.QRect(390, 30, 251, 41))
        self.whentobackup.setObjectName("whentobackup")
        self.When_select_btn = QtWidgets.QPushButton(self.frame_5)
        self.When_select_btn.setGeometry(QtCore.QRect(470, 100, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.When_select_btn.setFont(font)
        self.When_select_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.When_select_btn.setObjectName("When_select_btn")
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.keep_backup_label = QtWidgets.QLabel(self.frame_6)
        self.keep_backup_label.setGeometry(QtCore.QRect(50, 40, 199, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.keep_backup_label.setFont(font)
        self.keep_backup_label.setObjectName("keep_backup_label")
        self.keep_select_btn = QtWidgets.QPushButton(self.frame_6)
        self.keep_select_btn.setGeometry(QtCore.QRect(470, 90, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.keep_select_btn.setFont(font)
        self.keep_select_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.keep_select_btn.setObjectName("keep_select_btn")
        self.keepBackups = QtWidgets.QDateTimeEdit(self.frame_6)
        self.keepBackups.setGeometry(QtCore.QRect(390, 20, 251, 41))
        self.keepBackups.setObjectName("keepBackups")
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.Backup_frequency_label = QtWidgets.QLabel(self.frame_7)
        self.Backup_frequency_label.setGeometry(QtCore.QRect(50, 40, 261, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Backup_frequency_label.setFont(font)
        self.Backup_frequency_label.setObjectName("Backup_frequency_label")
        self.frequency = QtWidgets.QComboBox(self.frame_7)
        self.frequency.setGeometry(QtCore.QRect(390, 50, 251, 31))
        self.frequency.setObjectName("frequency")
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.body)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cancel_btn.setText(_translate("MainWindow", "Cancel"))
        self.schedule_label.setText(_translate("MainWindow", "Schedule"))
        self.back_btn.setText(_translate("MainWindow", "Back"))
        self.backup_btn.setText(_translate("MainWindow", "Backup"))
        self.when_backup_label.setText(_translate("MainWindow", "When to backup"))
        self.When_select_btn.setText(_translate("MainWindow", "Select"))
        self.keep_backup_label.setText(_translate("MainWindow", "Keep Backups"))
        self.keep_select_btn.setText(_translate("MainWindow", "Select"))
        self.Backup_frequency_label.setText(_translate("MainWindow", "Backup Frequency"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Page3_5_ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
